x-infra-logging: &infra-no-logs
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
      mode: "non-blocking"

services:
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfg
      POSTGRES_DB: sso_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  shortener-db:
    image: postgres:15
    container_name: shortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdfg
      POSTGRES_DB: shortener_db
    ports:
      - "5434:5432"
    volumes:
      - short_db_data:/var/lib/postgresql/data

  auth:
    build:
      context: .
      dockerfile: sso/Dockerfile
    depends_on:
      - auth-db
      - redis
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: asdfg
      DB_NAME: sso_db
      REDIS_ADDR: redis:6379
    tty: true
    stdin_open: true
    ports:
      - "44045:44045"
    volumes:
      - ./sso/config:/app/config

  shortener:
    build:
      context: .
      dockerfile: url-shortener/Dockerfile
    depends_on:
      - shortener-db
      - auth
    environment:
      DB_HOST: shortener-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: asdfg
      DB_NAME: shortener_db
      AUTH_SERVICE_URL: auth:8080
    tty: true
    stdin_open: true
    ports:
      - "8082:8080"
    volumes:
      - ./url-shortener/config:/app/config

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server
      --requirepass "asdfg"
    ports:
      - "6379:6379"
    <<: *infra-no-logs

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
    tty: true
    stdin_open: true
    ports:
      - "2181:2181"
    <<: *infra-no-logs

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: "WARN"
      KAFKA_LOG4J_LOGGERS: "kafka=WARN,org.apache.kafka=WARN,kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,kafka.request.logger=WARN,kafka.log.LogCleaner=WARN,state.change.logger=WARN,kafka.authorizer.logger=WARN,kafka.network.RequestChannel$=WARN"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "kafka:9092" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    <<: *infra-no-logs

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - LOGGING_LEVEL_ROOT=ERROR
    ports:
      - "9001:9000"
    depends_on:
      - kafka
    <<: *infra-no-logs

  analytics:
    build:
      context: .
      dockerfile: analytics/Dockerfile
    depends_on:
      - kafka
      - clickhouse
    environment:
      CONFIG_PATH: "/config.yaml"
      USER_PASS:
    tty: true
    stdin_open: true
    volumes:
      - ./analytics/config:/app/config

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: asdfg
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DEFAULT_HOST: "0.0.0.0"
      CLICKHOUSE_OPTS: "--listen_host=0.0.0.0"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s
    cap_add:
        - SYS_NICE
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    <<: *infra-no-logs

  clickhouse-client:
    image: clickhouse/clickhouse-server:23.8-alpine
    depends_on:
      - clickhouse
    entrypoint: [ "tail", "-f", "/dev/null" ]
    tty: true

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - clickhouse

volumes:
  auth_db_data:
  short_db_data:
  clickhouse_data:
  clickhouse_log: