env: "local" # dev, prod
token_ttl: 10m
r_token_ttl: 168h
grpc:
  port: 44045
  timeout: 10h

storage:
  host: "auth-db"
  port: 5432
  user: "postgres"
  password: "asdfg"
  dbname: "sso_db"
  sslmode: "disable"

redis:
  addr: "redis:6379"
  password: "asdfg"
  DB: 0

