env: "local" # local, dev, prod

storage:
  host: "shortener-db"
  port: 5432
  user: "postgres"
  password: "asdfg"
  dbname: "shortener_db"
  sslmode: "disable"
  token: "secret-key"

clients:
  sso:
    address: "auth:44045"
    timeout: 5s
    retries_count: 3

http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
  user: "lostmyescape"
  password: "asdfg"

redis:
  addr: "redis:6379"
  password: "asdfg"