name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-build:
    name: Test & Build Go services
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Start docker-compose
        run: |
          docker compose -f infra/docker-compose.yml up -d
          sleep 10

      - name: Test SSO service
        working-directory: ./sso
        run: go test ./... -v

      - name: Test Link Shortener service
        working-directory: ./link-shortener
        run: go test ./... -v

      - name: Test Analytics service
        working-directory: ./analytics
        run: go test ./... -v

      - name: Build sso
        run: go build -o sso ./sso/cmd/sso/main.go

      - name: Build url-shortener
        run: go build -o url-shortener ./url-shortener/cmd/main.go

      - name: Build analytics
        run: go build -o analytics ./analytics/cmd/main.go

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Build Docker images
        run: |
          docker build -t sso ./sso
          docker build -t url-shortener ./url-shortener
          docker build -t analytics ./analytics